spring:
  profiles:
    active: dev
  application:
    name: class-detect
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yupi?serverTimezone=Asia/Shanghai
    username: root
    password: 135790
  # session 过期时间(分钟)
  session:
    timeout: 86400
    store-type: redis

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  #  redis配置
  redis:
    database: 0
    host: localhost
    port: 6379
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB

server:
  port: 9898
  servlet:
    context-path: /api
    session:
      # 设置 cookie 作用域
      cookie:
        domain: localhost

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: is_delete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #在控制台开启输出sql日志

# 请求预测的地址
detect:
  headUrl: http://10.190.0.30:2580/yolov5sHead
  upDownUrl: http://10.190.0.30:2580/yolov5sUpDown
